---
- hosts: localhost,all
  
  connection: local
  vars:
      instance_type: t2.micro
      security_group: guerdon_security_group
      image: ami-04b9e92b5572fa0d1
      region: us-east-1
      keypair: guerdon-key
      subnet: subnet-11f6b476
      user: "ec2-user"
  tasks:
    - name: Create an EC2 key
      ec2_key:
        name: "{{ keypair }}"
        region: "{{ region }}"
      register: ec2_key
    
    - debug:
        var: ec2_key

    - name: save private key
      copy: content="{{ ec2_key.key.private_key }}" dest="./keys/guerdon-key.pem" mode=0600
      when: ec2_key.changed

    - name: Provision a new EC2 instance for Guerdon
      local_action: ec2
                    group={{security_group}}
                    instance_type=t2.micro 
                    image={{ image }}
                    wait=true
                    wait_timeout=1000 
                    region={{ region }}
                    keypair={{ keypair }}
                    count=1
                    monitoring=true
                    vpc_subnet_id={{ subnet }}
                    assign_public_ip=true
      register: ec2Instance

    - name: Add tag to Instance(s)
      local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
      with_items: "{{ ec2Instance.instances }}"
      args:
        tags:
          Name: GuerdonBotServer
    
    - debug:
        var: ec2Instance

    - name: Create inventory file with the public ip
      copy: content="[webserver]{{'\n'}}{{ item.public_dns_name }}{{' ansible_ssh_private_key_file=./keys/guerdon-key.pem\n'}}" dest=./inventory
      with_items: "{{ ec2Instance.instances }}"
    
    - name: Create a ssh forward agent for github
      copy: content="Host {{ item.public_dns_name }}{{'\n  ForwardAgent yes'}}" dest=./.ssh/config
      with_items: "{{ ec2Instance.instances }}"