MOCK_MODEL1_URL = "https://drive.google.com/file/d/1LaHmArTRo0aqNum6aoAwN-hyaYGGjY29/view?usp=sharing"
MOCK_MODEL2_URL = "https://drive.google.com/file/d/1LaHmArTRo0aqNum6aoAwN-hyaYGGjY29/view?usp=sharing"
MOCK_DATASET_URL = "https://docs.google.com/spreadsheets/d/1IxE0N_AWGwqD1cZ6odHYPDe5R0pTYm2BU1zli_VTi0I/edit?usp=sharing"
MOCK_BAD_URL = "https://BADURL/FakeNews.csv"
MOCK_EMAIL = "hackoverflow22@gmail.com"